from pathlib import Path

# MobileRemoteClient: exchange a 4-digit PIN once for the long bearer token.
p = Path('app/src/main/java/com/jarvis/tv/MobileRemoteClient.kt')
s = p.read_text()

if 'fun pair(pin: String)' not in s:
    anchor = '    fun ping(): JSONObject = get("/ping")\n\n'
    block = r'''    fun pair(pin: String): JSONObject {
        val clean = pin.trim()
        if (!clean.matches(Regex("\\d{4}"))) throw IllegalArgumentException("El PIN debe tener 4 dígitos")
        val result = get("/pair?pin=${URLEncoder.encode(clean, "UTF-8")}")
        val newToken = result.optString("token").trim()
        if (!result.optBoolean("paired") || newToken.isBlank()) throw IllegalStateException("El móvil no devolvió una sesión válida")
        prefs.edit().putString("mobile_remote_token", newToken).apply()
        return result
    }

'''
    if anchor not in s:
        raise SystemExit('ping anchor not found in MobileRemoteClient')
    s = s.replace(anchor, anchor + block, 1)
p.write_text(s)

# MainActivity generated by apply_tv_companion: ask for IP + short PIN, not a visible long token.
p = Path('app/src/main/java/com/jarvis/tv/MainActivity.kt')
s = p.read_text()

s = s.replace('val mobileToken = edit("Token Remote de Jarvis Mobile", prefs.getString("mobile_remote_token", "").orEmpty())',
              'val mobilePin = edit("PIN de 4 dígitos de Jarvis Mobile", "")')

old_test = r'''        val testMobileButton = Button(this).apply { text = "PROBAR CONEXIÓN CON MÓVIL"; setOnClickListener {
            prefs.edit().putString("mobile_remote_host", mobileHost.text.toString().trim()).putString("mobile_remote_token", mobileToken.text.toString().trim()).apply()
            Thread {
                runCatching { mobileRemote.ping() }
                    .onSuccess { runOnUiThread { Toast.makeText(this@MainActivity, "Jarvis Mobile conectado", Toast.LENGTH_LONG).show() } }
                    .onFailure { e -> runOnUiThread { Toast.makeText(this@MainActivity, "Móvil: ${e.message}", Toast.LENGTH_LONG).show() } }
            }.start()
        } }'''
new_test = r'''        val testMobileButton = Button(this).apply { text = "EMPAREJAR CON MÓVIL"; setOnClickListener {
            val hostValue = mobileHost.text.toString().trim()
            val pinValue = mobilePin.text.toString().trim()
            prefs.edit().putString("mobile_remote_host", hostValue).apply()
            Thread {
                runCatching { mobileRemote.pair(pinValue) }
                    .onSuccess {
                        runCatching { mobileRemote.ping() }
                        runOnUiThread { Toast.makeText(this@MainActivity, "Jarvis Mobile emparejado ✓", Toast.LENGTH_LONG).show() }
                    }
                    .onFailure { e -> runOnUiThread { Toast.makeText(this@MainActivity, "Emparejamiento: ${e.message}", Toast.LENGTH_LONG).show() } }
            }.start()
        } }'''
if old_test in s:
    s = s.replace(old_test, new_test, 1)

s = s.replace('box.addView(name); box.addView(wake); box.addView(backend); box.addView(mobileHost); box.addView(mobileToken); box.addView(testBackendButton); box.addView(testMobileButton);',
              'box.addView(name); box.addView(wake); box.addView(backend); box.addView(mobileHost); box.addView(mobilePin); box.addView(testBackendButton); box.addView(testMobileButton);')

s = s.replace('.putString("mobile_remote_host", mobileHost.text.toString().trim()).putString("mobile_remote_token", mobileToken.text.toString().trim()).apply(); showHome()',
              '.putString("mobile_remote_host", mobileHost.text.toString().trim()).apply(); showHome()')

p.write_text(s)
print('TV 4-digit mobile pairing patch applied')
