from pathlib import Path

# MobileRemoteClient: exchange a 4-digit PIN once for the long bearer token.
p = Path('app/src/main/java/com/jarvis/tv/MobileRemoteClient.kt')
s = p.read_text()

if 'fun pair(pin: String)' not in s:
    anchor = '    fun ping(): JSONObject = get("/ping")'
    block = r'''    fun pair(pin: String): JSONObject {
        val clean = pin.trim()
        if (!clean.matches(Regex("\\d{4}"))) throw IllegalArgumentException("El PIN debe tener 4 dígitos")
        val result = get("/pair?pin=${URLEncoder.encode(clean, "UTF-8")}")
        val newToken = result.optString("token").trim()
        if (!result.optBoolean("paired") || newToken.isBlank()) throw IllegalStateException("El móvil no devolvió una sesión válida")
        prefs.edit().putString("mobile_remote_token", newToken).apply()
        return result
    }

'''
    pos = s.find(anchor)
    if pos >= 0:
        end = s.find('\n', pos)
        if end < 0:
            end = pos + len(anchor)
            s = s[:end] + '\n\n' + block + s[end:]
        else:
            s = s[:end + 1] + '\n' + block + s[end + 1:]
    else:
        fallback = '    fun sendTask('
        pos = s.find(fallback)
        if pos < 0:
            raise SystemExit('No safe insertion point for pair() in MobileRemoteClient')
        s = s[:pos] + block + s[pos:]
p.write_text(s)

# MainActivity generated by apply_tv_companion: ask for IP + short PIN, not a visible long token.
p = Path('app/src/main/java/com/jarvis/tv/MainActivity.kt')
s = p.read_text()

s = s.replace('val mobileToken = edit("Token Remote de Jarvis Mobile", prefs.getString("mobile_remote_token", "").orEmpty())',
              'val mobilePin = edit("PIN de 4 dígitos de Jarvis Mobile", "")')

old_test = r'''        val testMobileButton = Button(this).apply { text = "PROBAR CONEXIÓN CON MÓVIL"; setOnClickListener {
            prefs.edit().putString("mobile_remote_host", mobileHost.text.toString().trim()).putString("mobile_remote_token", mobileToken.text.toString().trim()).apply()
            Thread {
                runCatching { mobileRemote.ping() }
                    .onSuccess { runOnUiThread { Toast.makeText(this@MainActivity, "Jarvis Mobile conectado", Toast.LENGTH_LONG).show() } }
                    .onFailure { e -> runOnUiThread { Toast.makeText(this@MainActivity, "Móvil: ${e.message}", Toast.LENGTH_LONG).show() } }
            }.start()
        } }'''
new_test = r'''        val testMobileButton = Button(this).apply { text = "EMPAREJAR CON MÓVIL"; setOnClickListener {
            val hostValue = mobileHost.text.toString().trim()
            val pinValue = mobilePin.text.toString().trim()
            prefs.edit().putString("mobile_remote_host", hostValue).apply()
            Thread {
                runCatching { mobileRemote.pair(pinValue) }
                    .onSuccess {
                        runCatching { mobileRemote.ping() }
                        runOnUiThread { Toast.makeText(this@MainActivity, "Jarvis Mobile emparejado ✓", Toast.LENGTH_LONG).show() }
                    }
                    .onFailure { e -> runOnUiThread { Toast.makeText(this@MainActivity, "Emparejamiento: ${e.message}", Toast.LENGTH_LONG).show() } }
            }.start()
        } }'''
if old_test in s:
    s = s.replace(old_test, new_test, 1)

s = s.replace('box.addView(name); box.addView(wake); box.addView(backend); box.addView(mobileHost); box.addView(mobileToken); box.addView(testBackendButton); box.addView(testMobileButton);',
              'box.addView(name); box.addView(wake); box.addView(backend); box.addView(mobileHost); box.addView(mobilePin); box.addView(testBackendButton); box.addView(testMobileButton);')

s = s.replace('.putString("mobile_remote_host", mobileHost.text.toString().trim()).putString("mobile_remote_token", mobileToken.text.toString().trim()).apply(); showHome()',
              '.putString("mobile_remote_host", mobileHost.text.toString().trim()).apply(); showHome()')

p.write_text(s)
print('TV 4-digit mobile pairing patch applied')
