from pathlib import Path

def replace_function(text, signature, replacement):
    start=text.find(signature)
    if start<0:
        raise SystemExit(f'{signature} not found')
    brace=text.find('{',start)
    depth=0; ins=False; esc=False
    for i in range(brace,len(text)):
        ch=text[i]
        if ins:
            if esc: esc=False
            elif ch=='\\': esc=True
            elif ch=='"': ins=False
        else:
            if ch=='"': ins=True
            elif ch=='{': depth+=1
            elif ch=='}':
                depth-=1
                if depth==0:
                    return text[:start]+replacement+text[i+1:]
    raise SystemExit(f'end not found for {signature}')

# ---------- MainActivity ----------
p=Path('app/src/main/java/com/jarvis/tv/MainActivity.kt')
s=p.read_text()

field='    private var voicePlayer: MediaPlayer? = null\n'
if 'private var pendingTranslationLanguage:' not in s:
    if field not in s: raise SystemExit('voicePlayer field missing')
    s=s.replace(field,field+'    private var pendingTranslationLanguage: String? = null\n',1)

start_fn=r'''    private fun startTranslation(language: String = prefs.getString("translation_target", "es") ?: "es") {
        val lang=language.ifBlank{"es"}
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED) {
            pendingTranslationLanguage=lang
            prefs.edit().putString("translation_status","esperando permiso de micrófono").apply()
            ActivityCompat.requestPermissions(this, arrayOf(Manifest.permission.RECORD_AUDIO), REQ_TRANSLATION_AUDIO)
            return
        }
        pendingTranslationLanguage=null
        prefs.edit()
            .putString("translation_target",lang)
            .putString("translation_status","arrancando servicio de doblaje")
            .remove("translation_last_error")
            .apply()
        runCatching {
            ContextCompat.startForegroundService(
                this,
                Intent(this, TranslationService::class.java)
                    .setAction(TranslationService.ACTION_START)
                    .putExtra(TranslationService.EXTRA_LANGUAGE,lang)
            )
        }.onSuccess {
            Toast.makeText(this,"Doblaje arrancado · "+lang,Toast.LENGTH_SHORT).show()
        }.onFailure { e ->
            prefs.edit().putString("translation_status","error al arrancar: "+(e.message?:e.javaClass.simpleName)).apply()
            Toast.makeText(this,"No se pudo arrancar el doblaje: "+(e.message?:e.javaClass.simpleName),Toast.LENGTH_LONG).show()
        }
    }'''
s=replace_function(s,'    private fun startTranslation(',start_fn)

perm_fn=r'''    override fun onRequestPermissionsResult(requestCode: Int, permissions: Array<out String>, grantResults: IntArray) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        if (requestCode == REQ_AUDIO && grantResults.firstOrNull() == PackageManager.PERMISSION_GRANTED) {
            startVoiceInput()
        }
        if (requestCode == REQ_TRANSLATION_AUDIO) {
            if (grantResults.firstOrNull() == PackageManager.PERMISSION_GRANTED) {
                val lang=pendingTranslationLanguage ?: prefs.getString("translation_target","es") ?: "es"
                pendingTranslationLanguage=null
                startTranslation(lang)
            } else {
                pendingTranslationLanguage=null
                prefs.edit().putString("translation_status","permiso de micrófono denegado").apply()
                Toast.makeText(this,"El doblaje necesita permiso de micrófono",Toast.LENGTH_LONG).show()
            }
        }
        if (requestCode == REQ_CAMERA && grantResults.firstOrNull() == PackageManager.PERMISSION_GRANTED) startSofaVisionService()
    }'''
s=replace_function(s,'    override fun onRequestPermissionsResult(',perm_fn)

# Add dedicated request code.
s=s.replace(
    '        private const val REQ_AUDIO = 10\n',
    '        private const val REQ_AUDIO = 10\n        private const val REQ_TRANSLATION_AUDIO = 11\n'
)

# Add output + diagnostic buttons to final settings generated by v0.6.23.
needle='''        box.addView(Button(this).apply {
            text="DETENER DOBLAJE"
            setOnClickListener { stopTranslation();translationStatus.text="Estado: detenida" }
        })
'''
if needle in s and 'PROBAR SALIDA DE VOZ' not in s:
    add=needle+r'''        box.addView(Button(this).apply {
            text="PROBAR SALIDA DE VOZ"
            setOnClickListener {
                speakWithOpenAI("Prueba de voz de Javistv. Si escuchas esta frase, la salida de audio funciona correctamente.")
            }
        })
        box.addView(Button(this).apply {
            text="ACTUALIZAR DIAGNÓSTICO DE DOBLAJE"
            setOnClickListener {
                translationStatus.text=
                    "Estado: "+prefs.getString("translation_status","detenida")+
                    "\nIdioma: "+prefs.getString("translation_target","es")+
                    "\nBytes último audio: "+prefs.getLong("translation_last_chunk_bytes",0L)+
                    "\nOriginal: "+prefs.getString("translation_last_source","").orEmpty().take(180)+
                    "\nTraducción: "+prefs.getString("translation_last_text","").orEmpty().take(180)+
                    "\nMotor voz: "+prefs.getString("translation_voice_mode","").orEmpty().ifBlank{"sin generar"}+
                    "\nÚltimo error: "+prefs.getString("translation_last_error","").orEmpty().ifBlank{"ninguno"}
            }
        })
'''
    s=s.replace(needle,add,1)

s=s.replace('Ajustes de Javistv v0.6.23','Ajustes de Javistv v0.6.24')
p.write_text(s)

# ---------- TranslationService ----------
p=Path('app/src/main/java/com/jarvis/tv/TranslationService.kt')
t=p.read_text()

if 'import android.media.AudioAttributes' not in t:
    t=t.replace('import android.media.AudioManager\n','import android.media.AudioManager\nimport android.media.AudioAttributes\n',1)

# Capture with ambient-friendly source first.
rec_fn=r'''    private fun recordChunk(file: File, millis: Long) {
        var mr: MediaRecorder? = null
        var lastError: Throwable? = null
        val sources = intArrayOf(
            MediaRecorder.AudioSource.MIC,
            MediaRecorder.AudioSource.CAMCORDER,
            MediaRecorder.AudioSource.VOICE_RECOGNITION
        )
        for(source in sources) {
            try {
                mr=buildRecorder(file,source)
                mr.prepare()
                mr.start()
                recorder=mr
                prefs().edit().putString(
                    "translation_status",
                    "capturando audio · fuente "+when(source){
                        MediaRecorder.AudioSource.MIC -> "MIC"
                        MediaRecorder.AudioSource.CAMCORDER -> "CAMCORDER"
                        else -> "VOICE_RECOGNITION"
                    }
                ).apply()
                var remaining=millis
                while(running && remaining>0) {
                    val step=minOf(100L,remaining)
                    Thread.sleep(step)
                    remaining-=step
                }
                runCatching{mr.stop()}
                runCatching{mr.reset()}
                runCatching{mr.release()}
                if(recorder===mr)recorder=null
                prefs().edit().putLong("translation_last_chunk_bytes",file.length()).apply()
                return
            } catch(e:Throwable) {
                lastError=e
                runCatching{mr?.reset()}
                runCatching{mr?.release()}
                if(recorder===mr)recorder=null
                mr=null
                file.delete()
            }
        }
        throw IllegalStateException("No se pudo abrir una entrada de audio: "+(lastError?.message?:lastError?.javaClass?.simpleName.orEmpty()))
    }'''
t=replace_function(t,'    private fun recordChunk(',rec_fn)

# Capture loop diagnostics.
t=t.replace(
'''                if (!file.exists() || file.length() < MIN_AUDIO_BYTES) {
                    file.delete()
                    continue
                }
''',
'''                val bytes=file.length()
                prefs().edit().putLong("translation_last_chunk_bytes",bytes).apply()
                if (!file.exists() || bytes < MIN_AUDIO_BYTES) {
                    prefs().edit()
                        .putString("translation_status","audio demasiado pequeño · "+bytes+" bytes")
                        .putString("translation_last_error","No se está capturando voz suficiente del televisor")
                        .apply()
                    file.delete()
                    continue
                }
'''
)

# Translation and synth diagnostics.
t=t.replace(
'''                val transcript = result.optString("transcript").trim()
                val translated = result.optString("translation").trim()
''',
'''                val transcript = result.optString("transcript").trim()
                val translated = result.optString("translation").trim()
                prefs().edit()
                    .putString("translation_last_source",transcript.take(700))
                    .putString("translation_last_text",translated.take(1000))
                    .remove("translation_last_error")
                    .apply()
'''
)

t=t.replace(
'''            } catch (e: Throwable) {
                prefs().edit().putString(
                    "translation_status",
                    "traducción: " + (e.message ?: e.javaClass.simpleName).take(140)
                ).apply()
''',
'''            } catch (e: Throwable) {
                val detail=(e.message ?: e.javaClass.simpleName).take(220)
                prefs().edit()
                    .putString("translation_status","traducción: "+detail)
                    .putString("translation_last_error",detail)
                    .apply()
'''
)

t=t.replace(
'''        val mode = c.getHeaderField("X-Javistv-Voice-Mode") ?: "voice-match"
        return DubSegment(out, text, mode)
''',
'''        val mode = c.getHeaderField("X-Javistv-Voice-Mode") ?: "voice-match"
        prefs().edit()
            .putString("translation_voice_mode",mode)
            .remove("translation_last_error")
            .apply()
        return DubSegment(out, text, mode)
'''
)

# Playback attributes and full volume.
t=t.replace(
'''                player.setAudioStreamType(AudioManager.STREAM_MUSIC)
                player.setDataSource(segment.file.absolutePath)
''',
'''                if(Build.VERSION.SDK_INT>=21) {
                    player.setAudioAttributes(
                        AudioAttributes.Builder()
                            .setUsage(AudioAttributes.USAGE_MEDIA)
                            .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
                            .build()
                    )
                } else {
                    @Suppress("DEPRECATION")
                    player.setAudioStreamType(AudioManager.STREAM_MUSIC)
                }
                player.setVolume(1.0f,1.0f)
                player.setDataSource(segment.file.absolutePath)
'''
)

t=t.replace(
'''            } catch (e: Throwable) {
                prefs().edit().putString(
                    "translation_status",
                    "audio doblado: " + (e.message ?: e.javaClass.simpleName).take(120)
                ).apply()
''',
'''            } catch (e: Throwable) {
                val detail=(e.message ?: e.javaClass.simpleName).take(180)
                prefs().edit()
                    .putString("translation_status","audio doblado: "+detail)
                    .putString("translation_last_error",detail)
                    .apply()
'''
)

t=t.replace('setRequestProperty("User-Agent", "Javistv/0.6.22")','setRequestProperty("User-Agent", "Javistv/0.6.24")')
p.write_text(t)

print('Javistv 0.6.24 translation permission/capture/playback diagnostics applied')
