import crypto from 'crypto';

function key(){const raw=process.env.HOMEY_SESSION_SECRET||process.env.HOMEY_CLIENT_SECRET||'';if(!raw)throw new Error('HOMEY_SESSION_SECRET_not_configured');return crypto.createHash('sha256').update(raw).digest();}
function open(blob){const b=Buffer.from(String(blob||''),'base64url');const iv=b.subarray(0,12),tag=b.subarray(12,28),data=b.subarray(28);const d=crypto.createDecipheriv('aes-256-gcm',key(),iv);d.setAuthTag(tag);return JSON.parse(Buffer.concat([d.update(data),d.final()]).toString('utf8'));}
function seal(obj){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv);const data=Buffer.concat([c.update(JSON.stringify(obj),'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),data]).toString('base64url');}
async function refreshIfNeeded(state){let token=state.token||{};const age=Date.now()-(state.createdAt||0);if(age<50*60*1000&&token.access_token)return state;const id=process.env.HOMEY_CLIENT_ID,secret=process.env.HOMEY_CLIENT_SECRET;if(!id||!secret||!token.refresh_token)return state;const r=await fetch('https://api.athom.com/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Authorization':'Basic '+Buffer.from(`${id}:${secret}`).toString('base64')},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:token.refresh_token})});const next=await r.json().catch(()=>({}));if(!r.ok)throw new Error(next?.error_description||'homey_refresh_failed');return {token:next,createdAt:Date.now()};}
async function homeySession(access){const meR=await fetch('https://api.athom.com/user/me',{headers:{Authorization:`Bearer ${access}`}});const me=await meR.json().catch(()=>({}));if(!meR.ok)throw new Error(me?.error_description||'homey_user_failed');const homeys=Array.isArray(me.homeys)?me.homeys:[];const homey=homeys.find(h=>h.platform==='cloud')||homeys[0];if(!homey)throw new Error('no_homey_found');const dR=await fetch('https://api.athom.com/delegation/token?audience=homey',{method:'POST',headers:{Authorization:`Bearer ${access}`}});const delegation=await dR.json().catch(async()=>await dR.text());if(!dR.ok)throw new Error('homey_delegation_failed');const remote=homey.remoteUrl;if(!remote)throw new Error('homey_remote_url_missing');const sR=await fetch(`${remote}/api/manager/users/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:typeof delegation==='string'?delegation:delegation?.token||delegation})});const session=await sR.json().catch(async()=>await sR.text());if(!sR.ok)throw new Error('homey_session_failed');return {homey,remote,session:typeof session==='string'?session:session?.token||session};}
function simplifyDevices(obj){return Object.values(obj||{}).map(d=>({id:d.id||d._id,name:d.name||'Dispositivo',type:d.class||d.virtualClass||'other',zoneId:d.zone||null,capabilities:d.capabilities||[],state:Object.fromEntries(Object.entries(d.capabilitiesObj||{}).map(([k,v])=>[k,v?.value]))}));}
export default async function handler(req,res){
  try{
    const blob=String(req.headers['x-homey-session']||req.body?.session||'');if(!blob)return res.status(401).json({error:'homey_login_required'});
    let state=await refreshIfNeeded(open(blob));const hs=await homeySession(state.token.access_token);const auth={Authorization:`Bearer ${hs.session}`};
    if(req.method==='POST'){
      const {deviceId,capabilityId,value}=req.body||{};if(!deviceId||!capabilityId)return res.status(400).json({error:'device_and_capability_required'});
      const r=await fetch(`${hs.remote}/api/manager/devices/device/${encodeURIComponent(deviceId)}/capability/${encodeURIComponent(capabilityId)}`,{method:'PUT',headers:{...auth,'Content-Type':'application/json'},body:JSON.stringify({value})});const out=await r.json().catch(()=>({}));if(!r.ok)return res.status(r.status).json({error:'homey_control_failed',details:out});
    }
    const r=await fetch(`${hs.remote}/api/manager/devices/device`,{headers:auth});const raw=await r.json().catch(()=>({}));if(!r.ok)return res.status(r.status).json({error:'homey_devices_failed',details:raw});
    return res.status(200).json({connected:true,homey:{id:hs.homey._id||hs.homey.id,name:hs.homey.name,platform:hs.homey.platform},devices:simplifyDevices(raw),session:seal(state)});
  }catch(e){return res.status(500).json({error:'homey_error',message:e?.message||'Homey error'});}
}
